version: "3.9"  # optional since v1.27.0
services:
  web:
    container_name: php_apache
    build:
      context: .
      args:
        - SERVER_HOSTNAME=${SERVER_HOSTNAME}
        - USER_ID=${UID}
    ports:
      - "${SERVER_HOST_HTTP_PORT}:80"
      - "${SERVER_HOST_HTTPS_PORT}:443"
    volumes:
      - ./apache-server.crt:/etc/apache2/ssl/certs/apache-server.crt
      - ./apache-server.key:/etc/apache2/ssl/private/apache-server.key
      - ${VOLUME_SYMFONY_FILES}:/var/www/html
